# Generated by Django 5.1.4 on 2025-03-24 07:21

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('description', ckeditor.fields.RichTextField()),
                ('answer_description', models.CharField(max_length=500, null=True)),
                ('camp_category', models.CharField(choices=[('C', 'Conceptual'), ('A', 'Analytical '), ('M', 'Memory'), ('P', 'Practice')], max_length=1, null=True)),
                ('is_practice', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('openDate', models.DateField()),
                ('closeDate', models.DateField(blank=True, null=True)),
                ('maxMarks', models.IntegerField(blank=True, null=True)),
                ('isActive', models.BooleanField(default=True)),
                ('noOfAttempts', models.IntegerField(blank=True, default=2, null=True)),
                ('noOfQuestions', models.IntegerField(blank=True, null=True)),
                ('is_practice', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('value', models.IntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aura.question')),
            ],
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('attemptNo', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aura.quiz')),
            ],
        ),
        migrations.AddField(
            model_name='quiz',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aura.skill'),
        ),
        migrations.AddField(
            model_name='question',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aura.skill'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='tags',
            field=models.ManyToManyField(to='aura.tags'),
        ),
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aura.tags'),
        ),
        migrations.CreateModel(
            name='User_Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_score', models.CharField(max_length=4)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('quiz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aura.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Attempt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aura.attempt')),
                ('Option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aura.option')),
                ('Question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aura.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_score', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aura.user_score')),
            ],
        ),
    ]
