# Generated by Django 5.1.4 on 2025-03-24 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('track', '0008_discussion_discussion_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('company_type', models.CharField(choices=[('SERVICE', 'Service Based'), ('PRODUCT', 'Product Based')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='JobRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('package_in_LPA', models.DecimalField(decimal_places=2, max_digits=12)),
                ('job_description', models.TextField(max_length=300)),
                ('hiring_process', models.CharField(choices=[('CONTEST', 'Contest Hiring'), ('CAMPUS', 'Campus Hiring')], max_length=50)),
                ('year', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_roles', to='company.company')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_name', models.CharField(max_length=100)),
                ('round_number', models.PositiveIntegerField()),
                ('round_type', models.CharField(choices=[('SYSTEM', 'system'), ('VIRTUAL_FACE_TO_FACE', 'virtual_face_to_face'), ('FACE_TO_FACE', 'face_to_face')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('job_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_process', to='company.jobrole')),
            ],
        ),
        migrations.CreateModel(
            name='Round_Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_skills', to='company.interviewprocess')),
                ('skill_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_skills', to='company.skill')),
            ],
        ),
        migrations.CreateModel(
            name='Round_Skill_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
                ('tags', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_tags', to='track.tags')),
                ('round_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_skill', to='company.round_skills')),
            ],
        ),
        migrations.CreateModel(
            name='SalaryBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_range', models.CharField(help_text="e.g., '0-3 ', '3-6'", max_length=50, unique=True)),
                ('companies', models.ManyToManyField(help_text='Companies associated with this salary band', related_name='salary_bands', to='company.company')),
            ],
        ),
    ]
