# Generated by Django 5.1.4 on 2025-01-09 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solved_problem',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
