# Generated by Django 5.1.4 on 2025-03-11 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0004_course_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Problem Type')),
            ],
        ),
        migrations.CreateModel(
            name='UserProblemStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solved_count', models.PositiveIntegerField(default=0, verbose_name='Problems Solved')),
                ('attempted_count', models.PositiveIntegerField(default=0, verbose_name='Problems Attempted')),
                ('problem_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_stats', to='track.problemtype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'problem_type')},
            },
        ),
    ]
