# Generated by Django 5.1.4 on 2025-03-11 10:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0005_problemtype_userproblemstats'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProblemStats',
            new_name='ProblemStats',
        ),
    ]
