# Generated by Django 5.1.4 on 2025-03-12 04:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0006_rename_userproblemstats_problemstats'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='problemstats',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='problemstats',
            name='contest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='problem_stats', to='track.contest'),
        ),
        migrations.AlterUniqueTogether(
            name='problemstats',
            unique_together={('user', 'problem_type', 'contest')},
        ),
    ]
