# Generated by Django 5.1.4 on 2025-03-24 05:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0007_contest_alter_problemstats_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discussion_name', models.CharField(max_length=55)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='track.course')),
            ],
        ),
        migrations.CreateModel(
            name='discussion_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integrity_score', models.IntegerField(choices=[(0, 'Not Performe'), (1, 'Good'), (2, 'Proficient')], default=0)),
                ('communication_score', models.IntegerField(choices=[(0, 'Need Improvement'), (1, 'Manageable'), (2, 'Fluent')], default=0)),
                ('comments', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('discussion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='track.discussion')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='track.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
