# Generated by Django 5.1.4 on 2025-04-02 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0008_discussion_discussion_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='dmoj_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
