# Generated by Django 5.1.4 on 2025-05-06 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0009_contest_dmoj_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='discussion_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='profile',
            name='integrity_index',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='profile',
            name='no_of_discussion',
            field=models.IntegerField(default=0),
        ),
    ]
