# Generated by Django 5.1.4 on 2025-05-06 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0010_profile_discussion_score_profile_integrity_index_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='discussion_index',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='discussion_score',
            field=models.IntegerField(default=0),
        ),
    ]
